
import { Data } from './data';

var video = '#b10f2e'
var audio = '#0A8AB5'
var comunicazione = '#eac435'
var foto = '#0F5257'
var elettronica = '#5fad56'

var iconePath = './assets/DataImage/icone/'
var imgPath = './assets/DataImage/foto/'
var youtube = 'https://www.youtube.com/embed/'

export const DATA: Data[] =   [
  {
    id: 1,
    name: 'Super 8',
    description: 'Nel 1965 è stato introdotto il formato Super8 dall’azienda Kodak, ed è stato un periodo fondamentale per questo settore in quanto è stato il periodo di punta dell’home cinema. In questo periodo infatti tutti coloro che disponevano di una cinepresa si dilettavano nelle riprese di momenti della loro vita sia professionale che lavorativa.Tra i più famosi filmati girati in questo formato si ha il video dell’assassinio di John Fitzgerald Kennedy a Dallas. Questo formato, nonostante fornisse dei grandiosi risultati, era molto difficile da utilizzare. Infatti il caricamento dei film doveva accadere al buio e andava eseguito manualmente. Per questo motivo la Kodak decise di realizzare ed introdurre un formato più semplice da utilizzare. Questo nuovo formato doveva essere contenuto nelle cartucce e doveva sfruttare in maniera più logica ed intelligente lo spazio disponibile sulla pellicola. Il Super 8 mm nasce a seguito di queste necessità ed esigenze. La novità era l’introduzione di spazio sulla pellicola che registrasse anche la colonna sonora. Viene quindi standardizzato da Kodak la ripresa a 18 fotogrammi al secondo, a differenza dei precedenti 16.',
    shortDescription: 'La Super 8 millimetri, o semplicemente Super 8, è una videocamera che utilizza nello specifico il formato 8 millimetri, dal quale prende il nome.',
    category: 'video',
    dateFrom: '1965',
    dateTo: '1075',
    yearFrom: 1965,
    yearTo: 1975,
    author: 'Kodak',
    latitude: 45,
    longitude: -78,
    fill : video,
    image: imgPath+"super8.jpg",
    icon: iconePath+'super8.png',
    license : "",
    spot: youtube+'ly0mn0Jev4Y'
  },{
    id: 2,
    name: 'Betamax',
    description: 'Betamax rappresenta il primo sistema di registrazione video su supporto a nastro magnetico pensato per il mercato domestico. Pensato da Sony e immesso sul mercato alcuni anni prima del VHS, non fu in grado di imporsi come standard rispetto alle videocassette. Sony lanciò in Giappone nel 1975 due modelli di betamax, SL-6300 e LV-1801, mentre negli USA venne presentato il modello SL-7200. Dopo un anno e 30.000 prodotti venduti arrivò il VHS della JVC che sotto alcuni punti di vista risultava inferiore rispetto al Betamax. I prezzi dei VHS risultavano significativamente più bassi rispetto a Betamax e questo sancì la maggiore diffusione del primo. A fine 2002 Sony dichiarò che avrebbe prodotto ancora duemila videoregistratori Betamax entro qualche mese dopodichè avrebbe abbandonato il progetto. Nel gennaio 2003 fu ufficialmente cessata la produzione di videoregistratori Betamax. Successivamente il 10 novembre 2015 Sony annunciò la fine della produzione delle videocassette Betamax a partire da marzo 2016 dopo oltre 40 anni di presenza sul mercato.',
    shortDescription: 'Primo sistema di videoregistrazione a nastro magnetico, ideato appositamente per il mercato domestico. ',
    category: 'video',
    dateFrom: '10/05/1975',
    dateTo: '1/12/2002',
    yearFrom: 1975,
    yearTo: 2002,
    author: 'Sony',
    latitude: 36.5,
    longitude: 141,
    icon: iconePath+'betamax.png',
    image: imgPath+"betamax.jpeg",
    fill : video,
    license : "",
    spot: youtube+'suclT9u51Fc'
  },{
    id: 3,
    name: 'Formato VHS',
    description: 'Il Video Home System è un sistema di videoregistrazione standard in formato analogico su supporto meccanico. Inizialmente il nome derivava da “Vertical Helicoidal Scan” cioè la tecnica utilizzata per la lettura. JVC presentò il suo primo VHS a cassetta nel 1976 che divenne poi lo standard per la registrazione su nastro e la riproduzione di filmati analogici tramite videoregistratore. Questo apparecchio viste le ridotte dimensioni divenne lo strumento dominante per la registrazione domestica vendendo una notevole diffusione nelle case dei consumatori. La maggior diffusione rispetto al Betamax derivò dal minor costo dei videoregistratori VHS che divennero presto il sistema dominante del mercato. Durante gli anni 80 i videoregistratori VHS divennero stereofonici, guadagnando così un audio di migliore qualità. Negli stessi anni venne implementata  la modalità LP (long play) che permetteva, di raddoppiare la durata di registrazione, a discapito della qualità video, ma non di quella audio. Verso la fine degli anni novanta l’introduzione dei DVD e di altri supporti di registrazione digitale fecero lentamente ridurre la fetta di mercato del VHS. VHS è entrato ufficialmente nell’elenco delle tecnologie dimenticate nel luglio 2016 quando la Funai Electric, l’ultima azienda rimasta al mondo a produrre questo tipo di supporto cessò la produzione.',
    shortDescription: 'Sistema di videoregistrazione standard in formato analogico su supporto meccanico. ',
    category: 'video',
    dateFrom: '09/11/1976',
    dateTo: '2008',
    yearFrom: 1976,
    yearTo: 2008,
    author: 'JVC',
    latitude: 38,
    longitude: 140,
    fill : video,
    image: imgPath+"vhs.jpg",
    icon: iconePath+'vhs.png',
    license : "",
    spot: youtube+'pjXh-tNLqHQ'
  },{
    id: 4,
    name: 'Laserdisc',
    description: 'David Paul regg durante la fine degli anni cinquanta ha inventato la tecnologia che sta alla base del Laserdisc per la Gauss inc. Pochi anni dopo anche la Philips si è cimentata nella realizzazione di tecnologie Laserdisc. Ufficialmente nel 1978 è avvenuta la prima presentazione del Discovision e del primo dispositivo per leggere questa tecnologia, ovvero un lettore.Il tipo di dati contenuti nelle tecnologie Laserdisc è quello analogico, e non digitale - come invece siamo abituati oggi, inoltre riesce a contenere più tracce audio. Questo permette di ottenere una quantità di formato molto elevata, e può essere inoltre registrata su tutti e due i lati.',
    shortDescription: 'Simili ai classici CD, ma dalle dimensioni dei vinili.',
    category: 'video',
    dateFrom: '11/12/1978',
    dateTo: '1995',
    yearFrom: 1978,
    yearTo: 1995,
    author: 'David Paul Greg - James Russell',
    latitude: 33,
    longitude: -116,
    image: imgPath+"laserdisc.png",
    icon: iconePath+'laserdisc.png',
    fill : video,
    license:"",
    spot: youtube+'ZGjw3gUwMOo'
  },{
    id: 5 ,
    name: 'Grammofono',
    shortDescription: 'Sistema di registrazione e riproduzione del suono. ',
    description: 'Il grammofono è una tecnologia sviluppata intorno al 1870 ed aveva la funzione di registrare e di riprodurre dei suoni. La differenza dalle principali tecnologie precedenti è l’utilizzo dei dischi per la lettura e riproduzione di questi suoni. Questi dischi erano realizzati in vinile ed erano caratterizzati da una velocità tra i 33 e i 78 giri al minuto. Un motore elettrico procedeva nell’avviare la rotazione del piatto del disco, ed il valore di registrazione del disco era lo stesso valore di velocità a cui esso doveva girare. Una curiosa storia sulla creazione del grammofono riguarda la prima incisione: Edison infatti stava canticchiando <i>“Mary had a little lamb”</i>. Dopo diversi anni sono state create due diverse macchine che svolgessero le funzioni del grammofono originario: ovvero una tecnologia per l’incisione del suono e un’altra per la riproduzione.',
    category: 'audio',
    dateFrom: '1877',
    dateTo: '1929',
    yearFrom: 1877,
    yearTo: 1929,
    author: 'Thomas Edison',
    latitude: 40,
    longitude: -74,
    fill : audio,
    image: imgPath+"gramophone.jpg",
    icon: iconePath+'gramophone.png',
    license:"",
    spot: ''
  },{
    id: 6 ,
    name: 'Giradischi',
    description: 'Come il grammofono, il giradischi è un dispositivo per la riproduzione e l’incisione meccanica del suono, sviluppato però successivamente rispetto al primo e costruito con meccanismi più moderni. Il giradischi è composto da un piatto, ovvero la parte rotante su cui viene posizionato il vinile e di solito è in acrilico, un tappetino antiscivolo (oppure mat, dall’inglese), che funge da interfaccia tra giradischi e dischi, il contrappeso è un peso posizionato sul braccio e controlla la cartuccia nel suo monitoraggio, l’antitasking è un’altra parte applicata al braccio di lettura del giradischi e non è altro che la punta che poggia su disco in vinile, il meccanismo di cueing viene utilizzato per alzare e abbassare il braccio del giradischi, un perno di centraggio dove poter inserire il disco, la base del dispositivo ed un interruttore per regolare l’accensione o spegnimento.',
    shortDescription: 'Il giradischi è l\'evoluzione economica del grammofono.',
    category: 'audio',
    dateFrom: '1937',
    dateTo: '1997',
    yearFrom: 1937,
    yearTo: 1997,
    author: 'RCA Victor',
    latitude: 38, 
    longitude: -76,
    fill: audio,
    icon: iconePath+'giradischi.png',
    image: imgPath+"giradischi.jpg",
    license:"",
    spot: youtube+'apf_tjyRVfI'
  },{
    id: 7,
    name: 'Bobina Aperta',
    shortDescription: 'Supporto per la registrazione del suono / reel-to-reel',
    description: 'La bobina aperta, conosciuta anche in inglese come <i> reel to reel </i>, è un formato diverso rispetto a quello delle videocassette e delle musicassette in quanto è un nastro magnetico, ma lascia un’estremità del nastro libera. È diventata una tipologia di registrazione obsoleta da quanto, dall’inizio degli anni 2000 è stato introdotto il formato digitale. Le ultime macchine a bobine aperte che sono state prodotte sono stati i registratori Digital Audio Stationary Head, intorno al 1995. Il vantaggio della bobina aperta consisteva nella sua lunghezza, infatti permetteva delle sessioni di registrazioni estremamente lunghe, senza la necessità di interrompere le registrazioni dopo 30 minuti, come invece accadeva nel disco fonografico. Un altro punto a favore della bobina aperta era la possibilità di poter maneggiare le registrazioni audio come se fossero delle vere e proprie entità fisiche.',
    category: 'audio',
    dateFrom: '1950',
    dateTo: '2000',
    yearFrom: 1950,
    yearTo: 2000,
    author: 'AEG / Wollensak',
    latitude: 52,
    longitude: 13,
    image: imgPath+"taperecorder.jpg",
    icon: iconePath+'taperecorder.png',
    fill : audio,
    license : "",
    spot: youtube+'0V426FsFvX8'
  },{
    id: 8,
    name: 'Registratore a nastro',
    shortDescription: 'Dispositivo per la registrazione su cassette a nastro',
    description: ' In gergo è anche detto registratore magnetico, oppure anche magnetofono. Il registratore a nastro viene utilizzato per riprodurre e registrare dei suoni, ed il formato supportato da questo dispositivo è quello della bobina aperta, già trattato tra le tecnologie in disuso. La tecnologia precedente che il registratore a nastro è andata a sostituire è il grande registratore Siemens, che supportava delle bobine di grandi dimensioni, come quelle dei proiettori cinematografici 35mm.',
    category: 'audio',
    dateFrom: '1963',
    dateTo: '2000',
    yearFrom: 1963,
    yearTo: 2000,
    author: 'Philips',
    latitude: 52.5,
    longitude: 7,
    fill: audio,
    image: imgPath+"registr_nastro.jpg",
    icon: iconePath+'registr_nastro.png',
    license : "",
    spot: ''
  },{
    id: 9 ,
    name: 'Radio Transistor',
    shortDescription: 'Dispositivo audio con circuito a transistor',
    description: 'La radio transistor è un piccolo dispositivo di ricezione radio portatile utilizza un circuito basato sul conduttore transistor. Questi dispositivi sono diventati tra i più popolari mezzi di comunicazione della storia intorno alla metà del 1900, con milioni di dispositivi realizzati tra il 1960 e il 1970. La loro dimensione ridotta li ha resi davvero indispensabili in quel periodo, cambiando le abitudini della popolazione nell’ascoltare la musica - soprattutto essendo dei dispositivi portatili e permettendo alle persone di ascoltare i loro artisti preferiti. ',
    category: 'audio',
    dateFrom: '1954',
    dateTo: 'ancora in uso',
    yearFrom: 1954,
    yearTo: 2019,
    author: 'Texas Instruments',
    latitude: 33,
    longitude: -97,
    image: imgPath+"radio.jpg",
    icon: iconePath+'radio.png',
    fill: audio,
    license : "",
    spot: youtube+'mO5d63WpNa8'
  },{
    id:10 ,
    name: 'Cassette',
    shortDescription: 'Supporto audio a nastro magnetico / compact cassette',
    description: 'Supporto per nastro magnetico analogico utilizzato per la registrazione e la riproduzione audio.',
    category: 'audio',
    dateFrom: '1962',
    dateTo: 'ancora in uso',
    yearFrom: 1962,
    yearTo: 2019,
    author: 'Philips',
    latitude: 51,
    longitude: 6,
    fill: audio,
    image: imgPath+"cassette.jpg",
    icon: iconePath+'cassette.png',
    license : "",
    spot: youtube+'EMN1FqYMbRw'
  },{
    id: 11,
    name: 'Ghetto Blaster',
    shortDescription: 'Stereo Portatile / Boombox',
    description: 'Stereo portatile con altoparlanti integrati in grado di riprodurre musicassette e sintonizzarsi su stazioni radio',
    category: 'audio',
    dateFrom: '1966',
    dateTo: '2003',
    yearFrom: 1966,
    yearTo: 2003,
    author: 'Philips',
    latitude: 52,
    longitude: 5,
    image: imgPath+"boombox.png",
    icon: iconePath+'boombox.png',
    fill: audio,
    license : "",
    spot: youtube+'xwpp5pNyKFo'
  },{
    id: 12,
    name:  'Telegrafo',
    shortDescription: 'Il telegrafo è un sistema di comunicazione a distanza',
    description: 'La comunicazione per mezzo del telegrafo è definita telegrafia e si distingue dal telefono e dalla telefonia, che è un sistema di trasmissione sviluppato successivamente, nato per il trasferimento di dati vocali e che nel tempo ha sostituito il telegrafo',
    category: 'comunicazione',
    dateFrom: '1793',
    dateTo: '21/06/2013',
    yearFrom: 1893,
    yearTo: 2013,
    author: 'Claude Chappe',
    latitude: 49,
    longitude: 2,
    image: imgPath+"telegraph.jpg",
    icon: iconePath+'telegraph.png',
    fill: comunicazione,
    license : "",
    spot: ''
  },{
    id: 13,
    name: 'Telex',
    description: 'Sistema di telecomunicazione',
    shortDescription: 'Un sistema di telecomunicazione sviluppato a partire dagli anni trenta e largamente usato nel XX secolo per la corrispondenza commerciale tra aziende',
    category: 'comunicazione',
    dateFrom: '1930',
    dateTo: '31/12/2001',
    yearFrom: 1930,
    yearTo: 2001,
    author: 'Servizio postale del Reich',
    latitude: 52,
    longitude: 52,
    fill: comunicazione,
    icon: iconePath+'telex.png',
    image: imgPath+"telex.png",
    license : "",
    spot: youtube+'byarX5L_Ki8'
  },{
    id: 14,
    name: 'Siemens S62',
    description: 'Telefono a disco',
    shortDescription: '',
    category: 'comunicazione',
    dateFrom: '1962',
    dateTo: '1985',
    yearFrom: 1962,
    yearTo: 1985,
    author: 'Siemens',
    latitude: 48,
    longitude: 11,
    fill: comunicazione,
    icon: iconePath+'s62.png',
    image: imgPath+"s62.jpg",
    license : "",
    spot: youtube+'jwO7Qr-O9OU'
  },{
    id: 15,
    name: 'Computer Palmare',
    description: 'PDA. E\' un computer di dimensioni contenute, tali da essere portato sul palmo di una mano, dotato di uno schermo tattile',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1984',
    dateTo: '2010',
    yearFrom: 1984,
    yearTo: 2010,
    author: 'Psion',
    latitude: 51,
    longitude: -0.5,
    image: imgPath+"palmare.jpg",
    icon: iconePath+'palmare.png',
    fill: elettronica,
    license : "",
    spot: youtube+'k6QjICoMgso'
  },{
    id: 16,
    name: 'Watchman',
    description: 'Televisore portatile',
    shortDescription: '',
    category: 'video',
    dateFrom: '1982',
    dateTo: '2000',
    yearFrom: 1982,
    yearTo: 2000,
    author: 'Sony',
    latitude: 36,
    longitude: 138.5,
    fill : video,
    image: imgPath+"watchman.jpeg",
    icon: iconePath+'portabletv.png',
    license : "",
    spot: youtube+'tdZ6LyaHJWI'
  },{
    id: 17,
    name: 'Walkman',
    description: 'lettore di musicassette',
    shortDescription: '',
    category: 'audio',
    dateFrom: '01/07/1979',
    dateTo: '22/10/2010',
    yearFrom: 1979,
    yearTo: 2010,
    author: 'Sony',
    latitude: 34.7,
    longitude: 139,
    icon: iconePath+'walkman.png',
    image: imgPath+"walkman.jpg",
    fill : audio,
    license : "",
    spot: youtube+'xOTfzZCyCmo'
  },{
    id: 18 ,
    name: 'Cercapersone',
    description: 'Pagers apparecchio elettronico precedente ai telefoni cellulare',
    shortDescription: '',
    category: 'comunicazione',
    dateFrom: '1949',
    dateTo: '2001',
    yearFrom: 1949,
    yearTo: 2001,
    author: '',
    latitude: 42,
    longitude: -71,
    fill: comunicazione,
    icon: iconePath+'pager.png',
    image: imgPath+"pager.jpg",
    license : "",
    spot: youtube+'jrUVYTqvIfI'
  },{
    id: 19,
    name: 'Pulsar',
    description: 'Primo orologio led',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1970',
    dateTo: '2019',
    yearFrom: 1970,
    yearTo: 2019,
    author: 'Hamilton e Electro/Data, Inc',
    latitude: 40.039722,
    longitude: -76.304444,
    fill: elettronica,
    icon: iconePath+'pulsar.png',
    image: imgPath+'pulsar.jpg',
    license: '',
    spot: youtube+'Ixj5125v4j8'
  }, {
    id: 20,
    name: 'TV Watch',
    description: '',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1982',
    dateTo: '2019',
    yearFrom: 1982,
    yearTo: 2019,
    author: 'Seiko',
    latitude: 35.683333,
    longitude: 139.683333,
    fill: elettronica,
    icon: iconePath+'tvwatch.png',
    image: imgPath+'tvwatch.jpg',
    license: '',
    spot: youtube+'5tIAPwyVuXI'
  },  {
    id: 21,
    name: 'Seiko Wrist Computer',
    description: '',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1984',
    dateTo: '2019',
    yearFrom: 1984,
    yearTo: 2019,
    author: 'Seiko',
    latitude: 36.683333,
    longitude: 140.683333,
    fill: elettronica,
    icon: iconePath+'seiko.png',
    image: imgPath+'seiko.jpg',
    license: '',
    spot: ''
  }, {
    id: 22,
    name: 'Calculator Watches',
    description: '',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1987',
    dateTo: '1997',
    yearFrom: 1987,
    yearTo: 1997,
    author: 'Casio',
    latitude: 35.689506,
    longitude: 139.6917,
    fill: elettronica,
    icon: iconePath+'calculatorwatch.png',
    image: imgPath+'calculatorwatch.jpg',
    license: '',
    spot: youtube+'jdwLdEv3z2Q'
  }, {
    id: 23,
    name: 'Monitor CTM',
    description: '',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1927',
    dateTo: '2004',
    yearFrom: 1927,
    yearTo: 2004,
    author: 'Philo Taylor Farnsworth',
    latitude: 39.065833,
    longitude: -123.445,
    fill: elettronica,
    icon: iconePath+'computer.png',
    image: imgPath+'computer.png',
    license: '',
    spot: ''
  }, {
    id: 24,
    name: 'Macchina da Scrivere',
    description: '',
    shortDescription: '',
    category: 'comunicazione',
    dateFrom: '1864',
    dateTo: '2019',
    yearFrom: 1864,
    yearTo: 2019,
    author: 'Peter Mitterhofer',
    latitude: 48.20833,
    longitude: 16.373064,
    fill: comunicazione,
    icon: iconePath+'typewriter.png',
    image: imgPath+'typewriter.jpg',
    license: '',
    spot: youtube+'7mxlroZT6no'
  },  {
    id: 25,
    name: 'Dial-up Modem',
    description: '',
    shortDescription: '',
    category: 'comunicazione',
    dateFrom: '1979',
    dateTo: '2019',
    yearFrom: 1979,
    yearTo: 2019,
    author: 'Tom Truscott-Steve Bellovin',
    latitude: 35.988611,
    longitude: -78.907222,
    fill: comunicazione,
    icon: iconePath+'harddrive.png',
    image: imgPath+'modem.jpg',
    license: '',
    spot: ''
  },  {
    id: 26,
    name: 'Zip Drive',
    description: '',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1994',
    dateTo: '2011',
    yearFrom: 1994,
    yearTo: 2011,
    author: 'Iomega',
    latitude: 33.02,
    longitude: -116.77,
    fill: elettronica,
    icon: iconePath+'zipdrive.png',
    image: imgPath+'zipdrive.jpeg',
    license: '',
    spot: youtube+'civsZLQzrjs'
  },  {
    id: 27,
    name: 'Proiettore di Diapositive',
    description: '',
    shortDescription: '',
    category: 'fotografia',
    dateFrom: '1960',
    dateTo: '2019',
    yearFrom: 1960,
    yearTo: 2019,
    author: 'Louis Misuraca - Kodak',
    latitude: 43.165556,
    longitude: -77.611389,
    fill: foto,
    icon: iconePath+'projector.png',
    image: imgPath+'projector.jpg',
    license: '',
    spot: youtube+'OEGiOHoTqfk'
  },  {
    id: 28,
    name: 'Floppy Disk',
    description: '',
    shortDescription: '',
    category: 'elettronica',
    dateFrom: '1967',
    dateTo: '2010',
    yearFrom: 1967,
    yearTo: 2010,
    author: 'IBM',
    latitude: 37.304167,
    longitude: -121.872778,
    fill: elettronica,
    icon: iconePath+'floppydisk.png',
    image: imgPath+'floppydisk.jpg',
    license: '',
    spot: youtube+'hJ0CebOs8aE'
  },  {
    id: 29,
    name: 'Polaroid',
    description: '',
    shortDescription: '',
    category: 'fotografia',
    dateFrom: '1948',
    dateTo: '2019',
    yearFrom: 1948,
    yearTo: 2019,
    author: 'Edwin H. Land',
    latitude: 42.460278,
    longitude: -71.348889,
    fill: foto,
    icon: iconePath+'polaroid.png',
    image: imgPath+'polaroid.jpg',
    license: '',
    spot: youtube+'mqLhZwbA3Ok'
  },  {
    id: 30,
    name: 'Proiettore cinematografico',
    description: '',
    shortDescription: '',
    category: 'video',
    dateFrom: '1879',
    dateTo: '1999',
    yearFrom: 1879,
    yearTo: 1999,
    author: 'Eadweard Muybridge',
    latitude: 51.507222,
    longitude: -0.1275,
    fill: video,
    icon: iconePath+'videoprojector.png',
    image: imgPath+'videoprojector.jpg',
    license: '',
    spot: youtube+'YaJndQhYiaI'
  }, {
    id: 31,
    name: 'Disco in Vinile',
    description: '',
    shortDescription: '',
    category: 'audio',
    dateFrom: '1948',
    dateTo: '2019',
    yearFrom: 1948,
    yearTo: 2019,
    author: 'Columbia Records',
    latitude: 40.716667,
    longitude: -74,
    fill: audio,
    icon: iconePath+'discovinile.png',
    image: imgPath+'discovinile.jpeg',
    license: '',
    spot: ''
  },  {
    id: 33,
    name: 'Stereo 8',
    description: '',
    shortDescription: '',
    category: 'audio',
    dateFrom: '1966',
    dateTo: '1983',
    yearFrom: 1966,
    yearTo: 1983,
    author: 'Bill Lear',
    latitude: 37.688889,
    longitude: -97.336111,
    fill: audio,
    icon: iconePath+'stereo8.png',
    image: imgPath+'stereo8.jpg',
    license: '',
    spot: youtube+'uovdc3C08gQ'
  }
]

  /**
   * {
    id: ,
    name: '',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: 1900,
    yearTo: 2019,
    author: '',
    latitude: 0,
    longitude: 0,
    fill: '',
    image: '',
    icon: '',
    license: ''
  }
  */
