
import { Data } from './data';

var video = '#b10f2e'
var audio = '#0A8AB5'
var comunicazione = '#eac435'
var foto = '#0F5257'
var computer = '#5fad56'

export const DATA: Data[] =   [
  {
    id: 1,
    name: 'Super 8',
    description: 'Nel 1965 è stato introdotto il formato Super8 dall’azienda Kodak, ed è stato un periodo fondamentale per questo settore in quanto è stato il periodo di punta dell’home cinema. In questo periodo infatti tutti coloro che disponevano di una cinepresa si dilettavano nelle riprese di momenti della loro vita sia professionale che lavorativa.Tra i più famosi filmati girati in questo formato si ha il video dell’assassinio di John Fitzgerald Kennedy a Dallas. Questo formato, nonostante fornisse dei grandiosi risultati, era molto difficile da utilizzare. Infatti il caricamento dei film doveva accadere al buio e andava eseguito manualmente. Per questo motivo la Kodak decise di realizzare ed introdurre un formato più semplice da utilizzare. Questo nuovo formato doveva essere contenuto nelle cartucce e doveva sfruttare in maniera più logica ed intelligente lo spazio disponibile sulla pellicola. Il Super 8 mm nasce a seguito di queste necessità ed esigenze. La novità era l’introduzione di spazio sulla pellicola che registrasse anche la colonna sonora. Viene quindi standardizzato da Kodak la ripresa a 18 fotogrammi al secondo, a differenza dei precedenti 16.',
    shortDescription: 'La Super 8 millimetri, o semplicemente Super 8, è una videocamera che utilizza nello specifico il formato 8 millimetri, dal quale prende il nome.',
    category: 'fotografia',
    dateFrom: 'year 1965',
    dateTo: 'year 1075',
    yearFrom: 1965,
    yearTo: 1975,
    author: 'Kodak',
    latitude: 43.157285,
    longitude: -77.615214,
    fill : foto,
    image: "./assets/DataImage/foto/super8.jpg",
    icon: './assets/DataImage/lomo-super-8.png',
    license : ""
  },{
    id: 2,
    name: 'Betamax',
    description: 'Betamax rappresenta il primo sistema di registrazione video su supporto a nastro magnetico pensato per il mercato domestico. Pensato da Sony e immesso sul mercato alcuni anni prima del VHS, non fu in grado di imporsi come standard rispetto alle videocassette. Sony lanciò in Giappone nel 1975 due modelli di betamax, SL-6300 e LV-1801, mentre negli USA venne presentato il modello SL-7200. Dopo un anno e 30.000 prodotti venduti arrivò il VHS della JVC che sotto alcuni punti di vista risultava inferiore rispetto al Betamax. I prezzi dei VHS risultavano significativamente più bassi rispetto a Betamax e questo sancì la maggiore diffusione del primo. A fine 2002 Sony dichiarò che avrebbe prodotto ancora duemila videoregistratori Betamax entro qualche mese dopodichè avrebbe abbandonato il progetto. Nel gennaio 2003 fu ufficialmente cessata la produzione di videoregistratori Betamax. Successivamente il 10 novembre 2015 Sony annunciò la fine della produzione delle videocassette Betamax a partire da marzo 2016 dopo oltre 40 anni di presenza sul mercato.',
    shortDescription: 'Primo sistema di videoregistrazione a nastro magnetico, ideato appositamente per il mercato domestico. ',
    category: 'video',
    dateFrom: '10/05/1975',
    dateTo: '1/12/2002',
    yearFrom: 1975,
    yearTo: 2002,
    author: 'Sony',
    latitude: 36,
    longitude: 140,
    icon: './assets/DataImage/betamax.png',
    image: "./assets/DataImage/foto/betamax.jpeg",
    fill : video,
    license : ""
  },{
    id: 3,
    name: 'Formato VHS',
    description: 'Il Video Home System è un sistema di videoregistrazione standard in formato analogico su supporto meccanico. Inizialmente il nome derivava da “Vertical Helicoidal Scan” cioè la tecnica utilizzata per la lettura. JVC presentò il suo primo VHS a cassetta nel 1976 che divenne poi lo standard per la registrazione su nastro e la riproduzione di filmati analogici tramite videoregistratore. Questo apparecchio viste le ridotte dimensioni divenne lo strumento dominante per la registrazione domestica vendendo una notevole diffusione nelle case dei consumatori. La maggior diffusione rispetto al Betamax derivò dal minor costo dei videoregistratori VHS che divennero presto il sistema dominante del mercato. Durante gli anni 80 i videoregistratori VHS divennero stereofonici, guadagnando così un audio di migliore qualità. Negli stessi anni venne implementata  la modalità LP (long play) che permetteva, di raddoppiare la durata di registrazione, a discapito della qualità video, ma non di quella audio. Verso la fine degli anni novanta l’introduzione dei DVD e di altri supporti di registrazione digitale fecero lentamente ridurre la fetta di mercato del VHS. VHS è entrato ufficialmente nell’elenco delle tecnologie dimenticate nel luglio 2016 quando la Funai Electric, l’ultima azienda rimasta al mondo a produrre questo tipo di supporto cessò la produzione.',
    shortDescription: 'Sistema di videoregistrazione standard in formato analogico su supporto meccanico. ',
    category: 'video',
    dateFrom: '09/11/1976',
    dateTo: 'year 2008',
    yearFrom: 1976,
    yearTo: 2008,
    author: 'JVC',
    latitude: 35.444991,
    longitude: 139.636768,
    fill : video,
    image: "./assets/DataImage/foto/VHS-cassette.jpg",
    icon: './assets/DataImage/vhs.png',
    license : ""
  },{
    id: 4,
    name: 'Laserdisc',
    description: 'David Paul regg durante la fine degli anni cinquanta ha inventato la tecnologia che sta alla base del Laserdisc per la Gauss inc. Pochi anni dopo anche la Philips si è cimentata nella realizzazione di tecnologie Laserdisc. Ufficialmente nel 1978 è avvenuta la prima presentazione del Discovision e del primo dispositivo per leggere questa tecnologia, ovvero un lettore.Il tipo di dati contenuti nelle tecnologie Laserdisc è quello analogico, e non digitale - come invece siamo abituati oggi, inoltre riesce a contenere più tracce audio. Questo permette di ottenere una quantità di formato molto elevata, e può essere inoltre registrata su tutti e due i lati.',
    shortDescription: 'Simili ai classici CD, ma dalle dimensioni dei vinili.',
    category: 'video',
    dateFrom: '11/12/1978',
    dateTo: 'year 1995',
    yearFrom: 1978,
    yearTo: 1995,
    author: 'David Paul Greg - James Russell',
    latitude: 33.839722 ,
    longitude: -118.259722 ,
    image: "./assets/DataImage/foto/laserdisc.png",
    icon: '',
    fill : video,
    license:""
  },{
    id: 5 ,
    name: 'Grammofono',
    description: 'Sistema di registrazione e riproduzione del suono. ',
    shortDescription: 'Questo strumento permetteva di registrare suoni e melodie su degli appositi dispositivi che lo supportavano, rendendo quindi possibile riascoltare ciò che si era inciso in precedenza. ',
    category: 'audio',
    dateFrom: 'year 1877',
    dateTo: 'year 1929',
    yearFrom: 1877,
    yearTo: 1929,
    author: 'Thomas Edison',
    latitude: 40.565,
    longitude: -74.3375 ,
    fill : audio,
    image: "./assets/DataImage/foto/Grammofono.jpg",
    icon: './assets/DataImage/old-gramophone.png',
    license:""
  },{
    id: 6 ,
    name: 'Giradischi',
    description: 'Dispositivi per registrare e ascoltare suoni e musica.',
    shortDescription: 'Il giradischi è l\'evoluzione economica del grammofono.',
    category: 'audio',
    dateFrom: 'year 1937',
    dateTo: 'year 1997',
    yearFrom: 1937,
    yearTo: 1997,
    author: 'RCA Victor',
    latitude: 39, 
    longitude: -76,
    fill: audio,
    icon: './assets/DataImage/icon/vinyl.png',
    image: "./assets/DataImage/foto/Giradischi.jpg",
    license:""
  },{
    id: 7,
    name: 'Bobina Aperta',
    description: 'Supporto per la registrazione del suono / reel-to-reel',
    shortDescription: 'La bobina aperta è un formato di nastro magnetico che lascia un\'estremità del nastro libera',
    category: 'audio',
    dateFrom: 'year 1950',
    dateTo: 'year 2000',
    yearFrom: 1950,
    yearTo: 2000,
    author: 'AEG',
    latitude: 52.5170365,
    longitude: 13.3888599,
    image: "./assets/DataImage/foto/bobinaAperta.jpg",
    icon: '',
    fill : audio,
    license : ""
  },{
    id: 8,
    name: 'Registratore a nastro / cassette-tape recorder',
    description: 'Dispositivo per la registrazione su cassette a nastro',
    shortDescription: ' In origine lanciato sul mercato nel come dispositivo per dettatura vocale progettato per uso portatile e successivamente utilizzato per la lettura delle cassette audio ',
    category: 'audio',
    dateFrom: 'year 1963',
    dateTo: 'year 2000',
    yearFrom: 1963,
    yearTo: 2000,
    author: 'Philips',
    latitude: 52.366667 ,
    longitude: 4.866667 ,
    fill: audio,
    image: "./assets/DataImage/foto/registratoreNastro.jpg",
    icon: '',
    license : ""
  },{
    id: 9 ,
    name: 'Radio Transistor',
    description: 'Dispositivo audio con circuito a transistor',
    shortDescription: 'Dispositivo di piccole dimensioni funzionante grazie ad circuito a transistor utilizzato per la riproduzione di segnali audio',
    category: 'audio',
    dateFrom: 'year 1954',
    dateTo: 'still in use',
    yearFrom: 1954,
    yearTo: 2019,
    author: 'Texas Instruments',
    latitude: 32.783333,
    longitude: -96.8,
    image: "./assets/DataImage/foto/radioTransistor.jpg",
    icon: './assets/DataImage/radio.png',
    fill: audio,
    license : ""
  },{
    id:10 ,
    name: 'Cassette',
    description: 'Supporto audio a nastro magnetico / compact cassette',
    shortDescription: 'Supporto per nastro magnetico analogico utilizzato per la registrazione e la riproduzione audio.',
    category: 'audio',
    dateFrom: 'year 1962',
    dateTo: 'still in use',
    yearFrom: 1962,
    yearTo: 2019,
    author: 'Philips',
    latitude: 50.93,
    longitude: 5.3375,
    fill: audio,
    image: "./assets/DataImage/foto/Compactcassette.jpg",
    icon: './assets/DataImage/cassette.png',
    license : ""
  },{
    id: 11,
    name: 'Ghetto Blaster',
    description: 'Stereo Portatile / Boombox',
    shortDescription: 'Stereo portatile con altoparlanti integrati in grado di riprodurre musicassette e sintonizzarsi su stazioni radio',
    category: 'audio',
    dateFrom: 'year 1966',
    dateTo: 'year 2003',
    yearFrom: 1966,
    yearTo: 2003,
    author: 'Philips',
    latitude: 52.366667,
    longitude: 4.866667,
    image: "./assets/DataImage/foto/boombox.png",
    icon: '',
    fill: audio,
    license : ""
  },{
    id: 12,
    name:  'Telegrafo',
    description: 'Il telegrafo è un sistema di comunicazione a distanza',
    shortDescription: 'La comunicazione per mezzo del telegrafo è definita telegrafia e si distingue dal telefono e dalla telefonia, che è un sistema di trasmissione sviluppato successivamente, nato per il trasferimento di dati vocali e che nel tempo ha sostituito il telegrafo',
    category: 'comunicazione',
    dateFrom: 'year 1793',
    dateTo: '21/06/2013',
    yearFrom: 1893,
    yearTo: 2013,
    author: 'Claude Chappe',
    latitude:48.856667,
    longitude:2.351944,
    image: "./assets/DataImage/foto/telegrafo.jpg",
    icon: './assets/DataImage/telegraph.png',
    fill: comunicazione,
    license : ""
  },{
    id: 13,
    name: 'Telex',
    description: 'Sistema di telecomunicazione',
    shortDescription: 'Un sistema di telecomunicazione sviluppato a partire dagli anni trenta e largamente usato nel XX secolo per la corrispondenza commerciale tra aziende',
    category: 'comunicazione',
    dateFrom: 'year 1930',
    dateTo: '31/12/2001',
    yearFrom: 1930,
    yearTo: 2001,
    author: 'Servizio postale del Reich',
    latitude:52.516667 ,
    longitude:52.516667,
    fill: comunicazione,
    icon: '',
    image: "./assets/DataImage/foto/olivetti.png",
    license : ""
  },{
    id: 14,
    name: 'Siemens S62,',
    description: 'Telefono a disco',
    shortDescription: '',
    category: 'comunicazione',
    dateFrom: 'year 1962',
    dateTo: 'year 1985',
    yearFrom: 1962,
    yearTo: 1985,
    author: 'Siemens',
    latitude: 48.137194 ,
    longitude: 11.5755,
    fill: comunicazione,
    icon: '',
    image: "./assets/DataImage/foto/s62.jpg",
    license : ""
  },{
    id: 15,
    name: 'Computer Palmare',
    description: 'PDA. E\' un computer di dimensioni contenute, tali da essere portato sul palmo di una mano, dotato di uno schermo tattile',
    shortDescription: '',
    category: 'computer',
    dateFrom: '',
    dateTo: 'year 2010',
    yearFrom: 1984,
    yearTo: 2010,
    author: 'Psion',
    latitude: 51.1121679,
    longitude: -0.5720182,
    image: "./assets/DataImage/foto/Apple_Newton.jpg",
    icon: '',
    fill: computer,
    license : ""
  },{
    id: 16,
    name: 'Watchman',
    description: 'televisore portatile',
    shortDescription: '',
    category: 'video',
    dateFrom: 'year 1982',
    dateTo: 'year 2000',
    yearFrom: 1982,
    yearTo: 2000,
    author: 'Sony',
    latitude: 34,
    longitude: 138,
    fill : video,
    image: "./assets/DataImage/foto/watchman.jpeg",
    icon: '',
    license : ""
  },{
    id: 17,
    name: 'Walkman',
    description: 'lettore di musicassette',
    shortDescription: '',
    category: 'audio',
    dateFrom: '01/07/1979',
    dateTo: '22/10/2010',
    yearFrom: 1979,
    yearTo: 2010,
    author: 'Sony',
    latitude: 34.5,
    longitude: 139.239128,
    icon: '',
    image: "./assets/DataImage/foto/walkman.jpg",
    fill : audio,
    license : ""
  },{
    id: 18 ,
    name: 'Cercapersone',
    description: 'Pagers apparecchio elettronico precedente ai telefoni cellulare',
    shortDescription: '',
    category: 'comunicazione',
    dateFrom: 'year 1949',
    dateTo: 'year 2001',
    yearFrom: 1949,
    yearTo: 2001,
    author: '',
    latitude: 40.6906512,
    longitude: -74.2534548,
    fill: comunicazione,
    icon: '',
    image: "./assets/DataImage/foto/motorola.jpg",
    license : ""
  },
]/*{
    id: 19,
    name: 'Pulsar',
    description: 'Primo orologio led',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude: ,
    fill: '',
    icon: '',
  }, {
    id: 20,
    name: 'TV Watch',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 21,
    name: 'Seiko Wrist Computer',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  }, {
    id: 22,
    name: 'Calculator Watches',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  }, {
    id: 23,
    name: 'Monitor a Tubo Catodico',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  }, {
    id: 24,
    name: 'Macchina da Scrivere',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 25,
    name: 'Dial-up Modem',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 26,
    name: 'Zip Drive',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 27,
    name: 'Proiettore di Diapositive',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 28,
    name: 'Floppy Disk',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 29,
    name: 'Polaroid',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 30,
    name: 'Videoproiettore a nastro',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  }, {
    id: 31,
    name: 'Disco in Vinile',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 32,
    name: 'Televisione a Tubo Catodico',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  },  {
    id: 33,
    name: 'Stereo8',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  }
]

  /**
   * {
    id: ,
    name: '',
    description: '',
    shortDescription: '',
    category: '',
    dateFrom: '',
    dateTo: '',
    yearFrom: ,
    yearTo: ,
    author: '',
    latitude: ,
    longitude:,
    fill: '',
    icon: '',
  }
  */

  /**
   * Tape Drives
   * {
    id: 18 ,
    name: 'Discman',
    description: 'Lettore cd',
    shortDescription: '',
    category: '',
    dateFrom: 'year 1984',
    dateTo: 'year 2019',
    yearFrom: 1984,
    yearTo: 201,
    author: 'Sony',
    latitude: 35.5,
    longitude:,
    fill: '',
    icon: '',
  }
  */